# Generated by Django 2.2.5 on 2020-04-23 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=80)),
                ('course_desc', models.CharField(max_length=200, verbose_name='course_description')),
                ('late_drop', models.DateField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Non-Binary')], max_length=3, null=True)),
                ('office_addr', models.CharField(max_length=60, verbose_name='office_address')),
                ('title', models.CharField(max_length=60)),
                ('dept_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NittanyPathApp.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Non-Binary')], max_length=3, null=True)),
                ('major', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zipcodes',
            fields=[
                ('zipcode', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TA_teaching_teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta_id', models.PositiveSmallIntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Students')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='zipcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='NittanyPathApp.Zipcodes'),
        ),
        migrations.CreateModel(
            name='ProfTeachingTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta_id', models.PositiveSmallIntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Professors')),
            ],
        ),
        migrations.CreateModel(
            name='ExamGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.PositiveSmallIntegerField()),
                ('exam_no', models.PositiveSmallIntegerField()),
                ('grades', models.PositiveSmallIntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Courses')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Students')),
            ],
        ),
        migrations.AddField(
            model_name='departments',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='NittanyPathApp.Professors'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_no', models.PositiveSmallIntegerField()),
                ('comment_no', models.PositiveSmallIntegerField()),
                ('comment_info', models.CharField(max_length=500)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Courses')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Students')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.PositiveSmallIntegerField()),
                ('limit', models.PositiveSmallIntegerField()),
                ('ta_id', models.PositiveSmallIntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Courses')),
            ],
            options={
                'unique_together': {('course_id', 'sec_no')},
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_no', models.PositiveSmallIntegerField()),
                ('post_info', models.CharField(max_length=500)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Courses')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Students')),
            ],
            options={
                'unique_together': {('email', 'course_id', 'post_no')},
            },
        ),
        migrations.CreateModel(
            name='Homeworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.PositiveSmallIntegerField()),
                ('hw_no', models.PositiveSmallIntegerField()),
                ('hw_details', models.CharField(max_length=200)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Courses')),
            ],
            options={
                'unique_together': {('course_id', 'sec_no', 'hw_no')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.PositiveSmallIntegerField()),
                ('hw_no', models.PositiveSmallIntegerField()),
                ('grades', models.PositiveSmallIntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Courses')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Students')),
            ],
            options={
                'unique_together': {('email', 'course_id', 'sec_no', 'hw_no')},
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.PositiveSmallIntegerField()),
                ('exam_no', models.PositiveSmallIntegerField()),
                ('exam_details', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Courses')),
            ],
            options={
                'unique_together': {('course_id', 'sec_no', 'exam_no')},
            },
        ),
        migrations.CreateModel(
            name='Enrolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_no', models.PositiveSmallIntegerField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Courses')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Students')),
            ],
            options={
                'unique_together': {('email', 'course_id', 'sec_no')},
            },
        ),
    ]
