# Generated by Django 2.2.5 on 2020-04-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NittanyPathApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_no', models.PositiveSmallIntegerField()),
                ('announcement_info', models.CharField(max_length=500)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Courses')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NittanyPathApp.Professors')),
            ],
            options={
                'unique_together': {('email', 'course_id', 'announcement_no')},
            },
        ),
    ]
